### ISSUE TITLE
Plugin fails with existing jobs

### ISSUE THREAD

**Issue by Kurisutian** [rundeck-plugins/jira-workflow-step#1]
I checked for an existing JIRA Ticket, using the plugin to test it with the Job you defined as an example. Every time I get the following error:

`[workflow] Begin execution: rundeck-workflow-node-first context: null
[workflow] Begin step: 1,JIRA-Issue-Exists
1: Workflow step executing: StepExecutionItem{type='JIRA-Issue-Exists', keepgoingOnSuccess=false, hasFailureHandler=false}
Issue key "${option.JiraTicket}".
Failed executing step plugin [JIRA-Issue-Exists]: com.dtolabs.rundeck.core.execution.workflow.steps.StepException: Issue key "${option.JiraTicket}".	at org.rundeck.plugins.workflow.JiraWorkflowStep.executeStep(JiraWorkflowStep.java:68)
	at com.dtolabs.rundeck.core.execution.workflow.steps.StepPluginAdapter.executeWorkflowStep(StepPluginAdapter.java:98)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:116)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWFItem(BaseWorkflowStrategy.java:225)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflowItemsForNodeSet(BaseWorkflowStrategy.java:303)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWFSection(NodeFirstWorkflowStrategy.java:313)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWorkflowImpl(NodeFirstWorkflowStrategy.java:119)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:182)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)

[workflow] Finish step: 1,JIRA-Issue-Exists
[workflow] Finish execution:  rundeck-workflow-node-first: [Workflow result: , step failures: {1=JiraIssueNotFound: Issue key "${option.JiraTicket}".}, status: failed]
[Workflow result: , step failures: {1=JiraIssueNotFound: Issue key "${option.JiraTicket}".}, status: failed]
Execution failed: 1767: [Workflow result: , step failures: {1=JiraIssueNotFound: Issue key "${option.JiraTicket}".}, status: failed]`

**Comment by ahonor** [comment]
Was their any related error message in the service.log?

**Comment by Kurisutian** [comment]
I checked out today and the debug output was the same. The service.log contained the following:
ERROR ExecutionUtilService - Execution failed: 1808: [Workflow result: , step failures: {1=JiraIssueNotFound: Issue key "LSAC-1112".}, status: failed]

**Comment by ultimatehem** [comment]
Is this issue addressed. Even i am facing the same error. My jira instance is of https://xxx.jira.com/ 
Error:[workflow] Begin step: 1,JIRA-Issue-Exists
20:45:32			1: Workflow step executing: StepExecutionItem{type='JIRA-Issue-Exists', keepgoingOnSuccess=false, hasFailureHandler=false}
20:45:33			Issue key "WBOPS-194".
20:45:33			Failed executing step plugin [JIRA-Issue-Exists]: com.dtolabs.rundeck.core.execution.workflow.steps.StepException: Issue key "WBDEVOPS-194".	at org.rundeck.plugins.workflow.JiraWorkflowStep.executeStep(JiraWorkflowStep.java:68)
	at com.dtolabs.rundeck.core.execution.workflow.steps.StepPluginAdapter.executeWorkflowStep(StepPluginAdapter.java:97)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:82)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWFItem(BaseWorkflowExecutor.java:360)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowStep(BaseWorkflowExecutor.java:732)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowItemsForNodeSet(BaseWorkflowExecutor.java:419)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWFSection(NodeFirstWorkflowExecutor.java:313)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:119)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:317)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)
20:45:33			[workflow] Finish step: 1,JIRA-Issue-Exists
20:45:33			[workflow] Finish execution:  node-first: [Workflow result: , step failures: {1=JiraIssueNotFound: Issue key "WBOPS-194".}, status: failed]
20:45:33			[Workflow result: , step failures: {1=JiraIssueNotFound: Issue key "WBDEVOPS-194".}, status: failed]
20:45:33			Execution failed: 4 in project FUSE_PROFILE_BACKUP: [Workflow result: , step failures: {1=JiraIssueNotFound: Issue key "WBOPS-194".},

**Comment by ahonor** [comment]
@ultimatehem Does that issue (eg, WBOPS-194) actually exist and it is failing incorrectly?

**Comment by ultimatehem** [comment]
Hello @Ahonor Thanks so much for the quick response. Yes the item exists and when i go to Jira portal and search the item it returns the item.

**Comment by ultimatehem** [comment]
@Kurisutian ,Please let me know if you found any solution to fix your issue. Thanks !

**Comment by Kurisutian** [comment]
@ultimatehem , I'm currently not using the plugin due to this error which I have not found a solution to make it work. Sorry.

**Comment by ultimatehem** [comment]
@Kurisutian Thank you so much for quick reply. Kindly let me know if you have any other alternate plugin for the same ?

**Comment by ultimatehem** [comment]
@ahonor ,kindly help in identifying the issue if this plugin works as expected and can be used for Rundeck jira integration

**Comment by marcjay** [comment]
Presumably this is an old issue that's no longer occurring? I wonder if the credentials being used to access Jira were for a user that does not have permissions on the appropriate project, and so cannot see the issues in that project?
